[package]
name = "vtasks"
version = "0.0.1"
edition = "2021"
author = "Davide Ceschia"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0"
tracing = "0.1"
tokio = { version = "1.0", features = ["full"] }
